Remove lowering functions and forklift
polysemy-research/polysemy pull request #438
Opened 2021-11-28 21:19 UTC by isovector

2021-11-29 17:47 UTC, KingoftheHomeless requested changes
The documentation needs a pass -- these are the ones I've been able to spot, but I suspect we've been mentioning lowering/forklift related stuff all over the place, and we should ensure such references go down the memory hole.

2021-11-29 17:47 UTC, KingoftheHomeless commented on src/Polysemy/Async.hs
>  --
Documentation for `asyncToIOFinal` must be updated.

2021-11-29 17:47 UTC, KingoftheHomeless commented on src/Polysemy/Resource.hs
>  {-# INLINE resourceToIOFinal #-}
The documentation for `resourceToIOFinal` must be updated.

2021-11-29 17:47 UTC, KingoftheHomeless commented on src/Polysemy.hs
>    , EffectRow
`.@`, `.@@` should be removed.

2021-11-29 18:23 UTC, isovector commented
@KingoftheHomeless PTAL. You were right, looking for the documentation to update found a few more things I should remove.

2021-11-30 22:06 UTC, isovector commented
I plan to merge this tomorrow unless there are any objections

2021-12-01 17:59 UTC, merged